apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maven-webapp.fullname" . }}
  labels:
    {{- include "maven-webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maven-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maven-webapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: ubuntu
          command:
          - sleep
          - infinity
          #image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
