FROM tomcat

RUN wget --no-check-certificate https://github.com/Chathuru/maven-web-project/releases/download/v1.0/maven-webapp.war -O /usr/local/tomcat/webapps/maven-webapp.war

CMD ["catalina.sh", "run"]
