name: (Optional) Dev Test

on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        default: true
        description: ''
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: |
          echo "${{ github.event.inputs.deploy }}"
          echo "*** ${{ github.event.ref }} ***"

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          check-latest: true
          cache: maven

      - name: Compile Project
        run: mvn package

      - name: Run Tests
        run: mvn test
        
      - run: docker build . -t maven-webapp
        if: ( ${{ github.event.inputs.deploy }} == "true" && success() )
        name: Login to Docker Hub
