name: (Optional) Dev Test

on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: cat README.md
        if: ${{ github.event.inputs.deploy }}

      - run: echo "*** ${{ github.event.ref }} ***"

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          check-latest: true
          cache: maven

      - name: Compile Project
        run: mvn compile

      - name: Run Tests
        run: mvn test
