name: (Optional) Dev Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
      branch_name:
        description: Name of the feature branch
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.name }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          check-latest: true
          cache: maven

      - name: Compile Project
        run: mvn compile

      - name: Run Tests
        run: mvn test
