name: Google Relese
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          command: github-release
      - uses: actions/checkout@v2
      - name: tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo v${{ steps.release.outputs.major }}
          echo v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
          echo "Release v${{ steps.release.outputs.major }}" 
      - name: release
        uses: chathuru/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0.0
          release_name: ${{ github.event.head_commit.message }}
          body: |
            Automated release
          draft: false
          prerelease: false
