name: Create Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: release
        uses: chathuru/create-release@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: ${{ github.event.head_commit.message }}
          body: |
            Automated release
          draft: false
          prerelease: false

      - name: Generate and email notes
        uses: Chathuru/jira-github-changelog@0.0.1
        id: changelog
        with:
          head: origin/master
          base: origin/dev
          jira-code: '(RP|RO)'
          jira-host: ${{ secrets.JIRA_HOST }}
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-password: ${{ secrets.JIRA_TOKEN }}
          pdf: false
          unshallow: false

      - name: Get the changelog message
        run: |
          export SUMMARY=$(echo '${{ steps.changelog.outputs.markdown }}' | jq '.markdown')
          printf "$SUMMARY"
          printf "$SUMMARY" > CHANGELOG.md
          printf "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Print
        run: cat CHANGELOG.md
