name: IF

on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        description: ''
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release-${{ env.GITHUB_RUN_NUMBER }}
        if: github.event.inputs.deploy
        run: |
          echo "${{ github.event.inputs.deploy }}"
          echo "*** ${{ github.event.ref }} ***"
      - if: ( ! github.event.inputs.deploy )
        run: |
          echo "Hi ..."
      - if: github.event.inputs.deploy == 'true'
        run: |
          echo "Hi ... true"
      - if: github.event.inputs.deploy == 'false'
        run: |
          echo "Hi ... false"
          echo ${{ github.ref }}
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo 'CMS'
          else
            echo 'BLT'
          fi
      - if: success() && (github.ref == 'refs/heads/dev')
        run: |
          echo ${{ github.ref }}
