name: testing web

on:
  workflow_dispatch:

jobs:
  apicafe_io:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - run:
          gem install jekyll bundler
          jekyll new myblog
          cd myblog
          
          
