name: MS Teams

on:
  workflow_dispatch:

jobs:
  apicafe_io:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "title": "No avaliable in here"
            }
