name: MS Teams

on:
  workflow_dispatch:

jobs:
  apicafe_io:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - uses: toko-bifrost/ms-teams-deploy-card@master
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

