name: testing web

on:
  workflow_dispatch:

jobs:
  apicafe_io:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - run:
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          gem install jekyll bundler
          jekyll new myblog
          cd myblog
          
          
