name: PR Sanity Check

on:
  pull_request:

jobs:
  build:
    name: PR Sanity Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.9.0
          cache: npm
          
      - name: Run Tests
        run: |
          echo $date
          
