name: maven-webapp-pr

on:
  pull_request:
    branches:
      - master

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          check-latest: true
          cache: maven

      - name: Compile Project
        run: mvn compile

      - name: Run Tests
        run: mvn test