name: maven-webapp-pr

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        default: false
        description: ''
        type: boolean

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          check-latest: true
          cache: maven

      - name: Compile Project
        run: mvn package

      - name: Login to Docker Hub
        run: docker build . -t maven-webapp
        if: ( github.event.inputs.deploy == 'true' && success() )
