name: maven-webapp-docker-release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          check-latest: true
      - name: Build with Maven
        run: mvn clean install
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build maven-webapp
        run: docker build . -t chathuru/maven-webapp
      - name: Push to Docker Hub
        run: docker push chathuru/maven-webapp:v13
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update Kubeconfig
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_NAME }}
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Sanity Check helm chart
        run: helm template webapp ./chart
      - name: Install helm chart
        run: helm upgrade --install webapp ./chart --wait
      - name: Rollback deployment on fail
        if: failure()
        run: helm rollback webapp
