name: maven-webapp-build-and-release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: zip -r stage.1.0.0.zip .

      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
        with:
          version: latest

      - name: Push Package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v1.0.2
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          debug: true
          ignore_ssl_errors: false
          log_level: debug
          overwrite_mode: IgnoreIfExists
          packages: stage.1.0.0.zip

      - name: Create Release in Octopus Deploy
        uses: OctopusDeploy/create-release-action@v1.0.4
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          debug: true
          project: stage
          deploy_to: stage
          package: stage:1.0.0
