name: Service Build Template

on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      aws_secrets:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Build ${{ inputs.service_name }} Service
      run: |
        echo ${{ inputs.service_name }}
        echo ${{ inputs.version }}
        echo ${{ secrets.aws_secrets }}
