name: SSH
on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        description: ''
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_KEY }}
          connect_timeout: 10s
          first_ssh: |
            cd /home/ubuntu/restrata-offline-resilience-parent
            docker-compose stop
            docker-compose rm -f docker-compose-qa.yml
            docker-compose -f docker-compose-qa.yml up -d
