name: SSH
on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        description: ''
        type: boolean
jobs:
  build:
    runs-on: offline-resilience-dev
    steps:
      - run: |
          cd /home/ubuntu/restrata-offline-resilience-parent
          docker-compose stop
          docker-compose rm -f docker-compose-qa.yml
          docker-compose -f docker-compose-qa.yml up -d
