name: SSH
on:
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        description: ''
        type: boolean
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: |
          cd /home/ubuntu/restrata-offline-resilience-parent
          docker-compose -f docker-compose-qa.yml stop
          docker-compose -f docker-compose-qa.yml rm
          docker-compose -f docker-compose-qa.yml up -d
